import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {MemoryRouter} from 'react-router-dom';
import AtlasMentor from '../components/academy/atlas/AtlasMentor';
const mocks=vi.hoisted(()=>({stop:vi.fn(),speak:vi.fn(),request:vi.fn()}));
vi.mock('@/hooks/useAuth',()=>({useAuth:()=>({user:{id:'reset-test'},profile:{display_name:'Student'}})}));
vi.mock('../components/academy/atlas/useAtlasVoice',()=>({useAtlasVoice:()=>({stop:mocks.stop,speak:mocks.speak,speaking:null,error:'',available:true})}));
vi.mock('@/integrations/supabase/localPreviewFetch',()=>({isLocalDesignPreview:()=>true,localPreviewFetch:mocks.request}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{}}));
const key='vault-atlas-preview-v1:reset-test';
const open=()=>act(()=>{window.dispatchEvent(new CustomEvent('toggle-coach-drawer'));});
beforeEach(()=>{sessionStorage.clear();vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({configured:false})}));Element.prototype.scrollIntoView=vi.fn();});
afterEach(()=>{cleanup();vi.unstubAllGlobals();vi.clearAllMocks();});
describe('Atlas New chat',()=>{
  it('clears history, chart, draft and practice, and stays empty after reopening',async()=>{
    sessionStorage.setItem(key,JSON.stringify([{id:'old',question:'My old demand question',answer:{title:'Old answer',text:'Old explanation',topic:'demand'}}]));
    render(<MemoryRouter><AtlasMentor/></MemoryRouter>);open();
    expect(screen.getByText('My old demand question')).toBeTruthy();
    expect(screen.getByRole('button',{name:'Show me what matters'})).toBeTruthy();
    fireEvent.change(screen.getByRole('textbox'),{target:{value:'Unsent draft'}});
    fireEvent.click(screen.getByRole('button',{name:'Start a new conversation'}));
    expect(screen.queryByText('Old explanation')).toBeNull();
    expect(screen.queryByRole('button',{name:'Show me what matters'})).toBeNull();
    expect((screen.getByRole('textbox') as HTMLTextAreaElement).value).toBe('');
    expect(document.activeElement).toBe(screen.getByRole('textbox'));
    expect(JSON.parse(sessionStorage.getItem(key)!)).toEqual([]);
    expect(mocks.stop).toHaveBeenCalled();
    open();open();
    expect(screen.queryByText('Old explanation')).toBeNull();
    expect(screen.queryByTestId('example-candle')).toBeNull();
  });
  it('ignores a late response from the conversation that was reset',async()=>{
    vi.mocked(fetch).mockResolvedValue({ok:true,json:async()=>({configured:true})} as Response);
    let resolve!:(value:unknown)=>void;
    mocks.request.mockImplementation(()=>new Promise(r=>{resolve=r;}));
    render(<MemoryRouter><AtlasMentor/></MemoryRouter>);open();
    await screen.findByText('AI mentor · Teaching references enabled');
    fireEvent.change(screen.getByRole('textbox'),{target:{value:'Explain demand'}});
    fireEvent.click(screen.getByRole('button',{name:'Send question'}));
    await waitFor(()=>expect(mocks.request).toHaveBeenCalled());
    const signal=mocks.request.mock.calls[0][1].signal;
    fireEvent.click(screen.getByRole('button',{name:'Start a new conversation'}));
    expect(signal.aborted).toBe(true);
    await act(async()=>{resolve({ok:true,json:async()=>({answer:'Stale response'})});});
    expect(screen.queryByText('Stale response')).toBeNull();
    expect(screen.queryByText('Working through your question…')).toBeNull();
    expect(JSON.parse(sessionStorage.getItem(key)!)).toEqual([]);
  });
});
