import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen} from '@testing-library/react';
import {SettingsProfile} from '../components/settings/SettingsProfile';
const mocks=vi.hoisted(()=>({from:vi.fn(),auth:{user:{id:'local-test'},profile:{display_name:'RZ',username:'rz',bio:'Learning together',avatar_url:'https://example.com/avatar.jpg'}}}));
vi.mock('@/hooks/useAuth',()=>({useAuth:()=>mocks.auth}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{from:mocks.from}}));
vi.mock('@/integrations/supabase/localPreviewFetch',()=>({isLocalDesignPreview:()=>true,localPreviewFetch:vi.fn()}));
vi.mock('sonner',()=>({toast:{success:vi.fn(),error:vi.fn(),info:vi.fn()}}));
afterEach(()=>{cleanup();sessionStorage.clear();vi.clearAllMocks();});
it('shows one profile preview and keeps avatar controls in a dialog',()=>{
 const {container}=render(<SettingsProfile/>);
 expect(container.querySelectorAll('.vs-identity-preview')).toHaveLength(1);
 expect(container.querySelectorAll('img')).toHaveLength(1);
 expect(screen.queryByRole('dialog')).toBeNull();
 fireEvent.click(screen.getByRole('button',{name:'Change avatar'}));
 expect(screen.getByRole('dialog')).toBeTruthy();
 fireEvent.click(screen.getByRole('button',{name:'Vault avatars'}));
 expect(screen.getAllByRole('button',{name:/Avatar icon/}).length).toBeGreaterThan(10);
 fireEvent.click(screen.getByRole('button',{name:'Use this avatar'}));
 expect(screen.queryByRole('dialog')).toBeNull();
 expect(mocks.from).not.toHaveBeenCalled();
});
it('saves and restores name and bio locally without updating a live profile',()=>{
 const view=render(<SettingsProfile/>);
 fireEvent.change(screen.getByLabelText('Display name'),{target:{value:'Preview RZ'}});
 fireEvent.change(screen.getByLabelText('Bio'),{target:{value:'My local biography'}});
 fireEvent.click(screen.getByRole('button',{name:'Save preview'}));
 expect(JSON.parse(sessionStorage.getItem('vault-profile-draft:local-test')!).bio).toBe('My local biography');
 view.unmount();render(<SettingsProfile/>);
 expect((screen.getByLabelText('Display name') as HTMLInputElement).value).toBe('Preview RZ');
 expect((screen.getByLabelText('Bio') as HTMLTextAreaElement).value).toBe('My local biography');
 expect(mocks.from).not.toHaveBeenCalled();
});
it('shows social fields, validates links, and restores or removes local social drafts',()=>{
 const view=render(<SettingsProfile/>);
 fireEvent.change(screen.getByLabelText('Instagram'),{target:{value:'@vault'}});
 fireEvent.change(screen.getByLabelText('YouTube'),{target:{value:'https://www.youtube.com/@vault'}});
 expect(screen.getByRole('link',{name:'Preview Instagram link'})).toHaveAttribute('href','https://instagram.com/vault');
 fireEvent.click(screen.getByRole('button',{name:'Save preview'}));
 view.unmount();render(<SettingsProfile/>);
 expect(screen.getByLabelText('Instagram')).toHaveValue('@vault');
 expect(screen.getByLabelText('YouTube')).toHaveValue('https://www.youtube.com/@vault');
 fireEvent.change(screen.getByLabelText('Instagram'),{target:{value:'https://evil.example/vault'}});
 fireEvent.click(screen.getByRole('button',{name:'Save preview'}));
 expect(screen.getByRole('alert')).toHaveTextContent('Enter an @handle');
 expect(JSON.parse(sessionStorage.getItem('vault-profile-draft:local-test')!).instagram).toBe('@vault');
 fireEvent.change(screen.getByLabelText('Instagram'),{target:{value:''}});
 fireEvent.click(screen.getByRole('button',{name:'Save preview'}));
 expect(JSON.parse(sessionStorage.getItem('vault-profile-draft:local-test')!).instagram).toBe('');
 expect(mocks.from).not.toHaveBeenCalled();
});
