import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, Check, Monitor, ChevronRight } from 'lucide-react';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { Checkbox } from '@/components/ui/checkbox';
import { useAcademyLessons } from '@/hooks/useAcademyLessons';
import { copyToClipboard } from '@/lib/copyToClipboard';
import { useTradingSetup } from './useTradingSetup';
import './trading-setup.css';

// Populate only with owner-verified destinations. Never guess referral or script URLs.
const links = {
  tradingViewInvite: import.meta.env.VITE_VAULT_TRADINGVIEW_INVITE_URL || '',
  indicator: import.meta.env.VITE_VAULT_INDICATOR_URL || '',
  ios: import.meta.env.VITE_VAULT_IOS_APP_URL || '',
};
function External({href,children,primary=false}:{href:string;children:React.ReactNode;primary?:boolean}) {
  return <a className={primary?'setup-primary':'setup-link'} href={href} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={16}/></a>;
}
function Walkthrough({pattern}:{pattern:RegExp}) {
  const { lessons, loading } = useAcademyLessons();
  const lesson = lessons.find(item => item.visible !== false && pattern.test(item.lesson_title));
  if (!lesson) return <p className="setup-note">{loading?'Loading your walkthrough…':'Walkthrough not available yet. Visit Learn for your setup lessons.'}</p>;
  let youtube = false;
  try { youtube = ['www.youtube.com','youtube.com','youtu.be'].includes(new URL(lesson.video_url).hostname); } catch {}
  return <div className="setup-walkthrough"><span>VAULT WALKTHROUGH</span><Link className="setup-link" to={`/academy/learn/${encodeURIComponent(lesson.module_slug)}?lesson=${encodeURIComponent(lesson.id)}`}>{lesson.lesson_title}<ChevronRight size={16}/></Link>{youtube && <External href={lesson.video_url}>Watch on YouTube</External>}</div>;
}
export function TradingSetupCard() {
  const { ready } = useTradingSetup();
  return <Link className={`setup-dashboard-card ${ready.length===5?'complete':''}`} to="/academy/setup"><span className="setup-card-icon">{ready.length===5?<Check size={22}/>:<Monitor size={22}/>}</span><span><strong>{ready.length===5?'Trading setup ready':'Before your first class'}</strong><small>{ready.length===5?'Review your charts, indicator, and class access.':`Get your charts, indicator, and class access ready. · ${ready.length} of 5 marked ready`}</small></span><b>{ready.length===5?'Review setup':'Set up for class'} <ChevronRight size={18}/></b></Link>;
}
export default function TradingSetup() {
  return <SetupChecklist/>;
}
function SetupChecklist() {
  const {ready,toggle,error} = useTradingSetup();
  const [active,setActive] = useState(String([0,1,2,3,4].find(i=>!ready.includes(i)) ?? 0));
  const [status,setStatus] = useState('');
  const [device,setDevice] = useState(/iPad|iPhone|iPod/.test(navigator.userAgent)?'ios':/Android/.test(navigator.userAgent)?'android':'desktop');
  const steps = [
    {title:'Set up TradingView',sub:'Your charts start here.',content:<><p>Create your account and open a chart. Keep your TradingView username handy for indicator access.</p><External href={links.tradingViewInvite || 'https://www.tradingview.com/'} primary>{links.tradingViewInvite?'Register with TradingView':'Open TradingView'}</External>{!links.tradingViewInvite&&<p className="setup-note">Vault’s invite link is pending. This button opens TradingView directly.</p>}<details><summary>Do I need Basic or Premium?</summary><p>TradingView Basic is free—no paid subscription needed. Start there for charting, or upgrade to a paid plan like Premium if you want more indicators per chart and custom timeframes. Vault indicator access is separate.</p></details><details><summary>Show me the setup walkthrough</summary><Walkthrough pattern={/TradingView Setup.*PT\.1/i}/></details></>},
    {title:'Add your Vault indicator',sub:'Open it. Add it to your chart. You’re ready.',content:<><p>This version is free to use. No access request or code download needed.</p>{links.indicator?<External href={links.indicator} primary>Open Vault indicator</External>:<button className="setup-primary" disabled>Indicator link pending</button>}<ol className="list-decimal pl-5 space-y-2 mb-5"><li>Open the indicator and sign in to TradingView if prompted.</li><li>Click “Use on chart” on the TradingView page.</li><li>Save your chart layout so it’s ready for your next session.</li></ol><p className="setup-note">Opens TradingView in a new tab. You finish adding it there; this button does not install it automatically.</p><details><summary>I can’t find the indicator</summary><p>Open TradingView and make sure you’re logged in. On your chart, click Indicators next to the timeframe selector. Search “Vault Trading Academy - Supply And Demand” (or just “Vault”), then choose the indicator by iretro123. Click it to add it to your chart, and click the star to save it to Favorites for easy access next time.</p><External href="https://www.tradingview.com/support/solutions/43000555216-how-to-try-indicators-and-strategies-from-the-community-on-your-chart/">TradingView’s indicator guide</External></details><details><summary>Show me the setup walkthrough</summary><Walkthrough pattern={/Vault OS Supply and Demand Indicator: Setup/i}/></details></>},
    {title:'Choose your practice or trading setup',sub:'Learning does not require a funded account.',content:<><p>Use TradingView to study charts. Your broker is where real orders are placed. You can attend Vault classes and practice without connecting or funding a brokerage account.</p><External href="https://www.tradingview.com/support/solutions/43000479975-how-to-connect-or-disconnect-a-paper-trading-account/" primary>Set up paper trading</External><details><summary>How does practice work?</summary><p>Open Supercharts, find the Trading panel, and choose Paper Trading. It uses simulated money. Practice fills are not a guarantee of real execution.</p><Walkthrough pattern={/How to Practice on TradingView/i}/></details><details><summary>I already have a broker</summary><p>Keep your broker’s app available alongside your chart. A direct TradingView connection is optional and depends on your broker. Confirm your account is in the intended practice or live mode before submitting any order. Never share your broker password with Vault.</p></details></>},
    {title:'Get ready for live classes',sub:'Get connected before the room starts.',content:<><p>Install Zoom and test your audio. Live Trading runs Monday–Thursday at 9:15 AM Eastern; Wednesday Class starts at 8 PM Eastern.</p><External href="https://zoom.us/download" primary>Download Zoom</External><div className="setup-actions"><External href="https://zoom.us/test">Test audio & video</External><Link className="setup-link" to="/academy/live?class=trading">Trading room <ChevronRight size={16}/></Link><Link className="setup-link" to="/academy/live?class=wednesday">Wednesday class <ChevronRight size={16}/></Link></div><details><summary>Before joining</summary><p>Run the Zoom test, check your headphones or speakers, and keep your chart nearby. Class times are Eastern; check the corresponding time where you live.</p></details></>},
    {title:'Keep Vault within reach',sub:'Make your next visit easy.',content:<><p>Keep Vault on your phone and save a shortcut on your computer.</p><div className="setup-device" aria-label="Your device">{['ios','android','desktop'].map(d=><button key={d} aria-pressed={device===d} onClick={()=>setDevice(d)}>{d==='ios'?'iPhone / iPad':d==='android'?'Android':'Desktop'}</button>)}</div>{device==='ios'?<>{links.ios?<External href={links.ios} primary>Download app now</External>:<><button className="setup-primary" disabled>App Store link pending</button><p className="setup-note">Waiting for the verified Vault App Store link.</p></>}<p>After installing, sign in and allow notifications when prompted. If you declined, check Settings → Notifications → Vault and turn on Allow Notifications. This checklist cannot verify delivery.</p></>:<><button className="setup-primary" onClick={async()=>setStatus(await copyToClipboard('https://member.vaulttradingacademy.com/')?'Vault link copied.':'Could not copy. Use the address shown below.')}>Copy Vault link</button><p className="setup-address">https://member.vaulttradingacademy.com/</p><p>{device==='android'?'Open Vault in your browser and use its menu to add a home-screen shortcut, if available. A shortcut does not guarantee push notifications.':'Open Vault in your browser and press Command+D on Mac or Ctrl+D on Windows to bookmark it. In Chrome or Edge, check the browser menu for an install option if available.'}</p></>}<details><summary>Already installed?</summary><p>Open Vault, make sure you’re signed in, and check notification permissions on your device. Marking this step ready does not install the app or turn notifications on.</p></details></>}
  ];
  return <main className="trading-setup"><Link to="/academy/home" className="setup-back">← Back to dashboard</Link><header><span className="setup-eyebrow">READY FOR THE ROOM</span><h1>Your Trading Setup</h1><p>Five steps to get ready to learn alongside Vault and trade with Vault.</p></header><div className="setup-progress"><strong>{ready.length} of 5 marked ready</strong><span>Self-reported · saved on this device</span><div aria-hidden="true">{steps.map((_,i)=><i key={i} className={ready.includes(i)?'done':''}/>)}</div></div><Accordion type="single" collapsible value={active} onValueChange={setActive}>{steps.map((step,i)=><AccordionItem key={i} value={String(i)} className="setup-step"><AccordionTrigger><span className={`setup-number ${ready.includes(i)?'done':''}`}>{ready.includes(i)?<Check size={21}/>:String(i+1).padStart(2,'0')}</span><span><strong>{step.title}</strong><small>{step.sub}</small></span></AccordionTrigger><AccordionContent><div className="setup-body">{step.content}<label className="setup-ready"><Checkbox checked={ready.includes(i)} onCheckedChange={()=>toggle(i)}/><span>{ready.includes(i)?'Marked as ready':'Mark as ready'}</span></label></div></AccordionContent></AccordionItem>)}</Accordion><p role="status" className="setup-note">{error||status}</p>{ready.length===5&&<div className="setup-finish"><Check size={23}/><div><h2>You’ve marked your setup ready.</h2><p>Bring your chart and your questions. We’ll see you in class.</p><Link to="/academy/live" className="setup-link">Go to Vault Live <ChevronRight size={17}/></Link></div></div>}<footer>You can learn at your own pace. Setup completion does not verify installation, indicator access, or notification delivery.</footer></main>;
}
