import React, { useState } from 'react';
import DailyChartStudy from './DailyStudyCard';
import { ArrowUpRight, Play, Video, MessageCircle, ChevronRight, Check, BookOpen } from 'lucide-react';

type Props = { act: (name: string) => void; memberName?: string; afterWelcome?: React.ReactNode };
const candles = [[164,183],[179,158],[162,139],[141,165],[162,191],[190,208],[207,189],[190,172],[174,155],[154,128],[128,143],[142,117],[116,95],[94,112],[111,85],[84,61],[62,78],[77,52],[53,68],[68,43]];
function StudyChart({reveal=true}:{reveal?:boolean}){return <svg className="tc-chart" viewBox="0 0 500 270" role="img" aria-label="Illustrative candlestick chart showing a bounce from a demand zone. Not live market data."><g stroke="#ffffff0d">{[45,90,135,180,225].map(y=><path key={y} d={`M20 ${y}H485`}/>)}{[40,120,200,280,360,440].map(x=><path key={x} d={`M${x} 20V245`}/>)}</g>{reveal&&<rect x="24" y="188" width="452" height="35" rx="4" fill="#80edc01b" stroke="#80edc05c" strokeDasharray="5 5"/>}{candles.map(([o,c],i)=><g key={i} stroke={c<o?'#83ecc1':'#ee8298'} fill={c<o?'#83ecc1':'#ee8298'}><path d={`M${42+i*21} ${Math.min(o,c)-11}V${Math.max(o,c)+10}`}/><rect x={36+i*21} y={Math.min(o,c)} width="12" height={Math.max(5,Math.abs(c-o))} rx="2"/></g>)}{reveal&&<><path d="M157 197Q215 256 292 221" fill="none" stroke="#c8ff8d" strokeWidth="2"/><text x="305" y="215" fill="#c8ff8d" fontSize="15" fontFamily="sans-serif">Demand zone</text></>}<text x="25" y="264" fill="#9da9bf" fontSize="12">ILLUSTRATIVE STUDY · NOT A LIVE PRICE FEED</text></svg>}
export default function TradingCampus({act,memberName,afterWelcome}:Props){const [revealed,setRevealed]=useState(false);const [interest,setInterest]=useState('Supply & demand');return <div className="tc">
  <header className="tc-welcome"><div><h1>Welcome back{memberName?.trim() ? `, ${memberName.trim()}` : ''}</h1><p>Come for the charts. Stay for the people.</p></div><span className="tc-member-label">VAULT MEMBER</span></header>
  {afterWelcome}
  <div className="tc-main-grid"><section className="tc-feature"><div className="tc-feature-copy"><span className="tc-pill"><Video size={15}/> VAULT LIVE</span><h2>Don’t just watch.<br/><em>Understand the move.</em></h2><p>Watch RZ work through the chart, ask your questions, and learn alongside the room.</p><div className="tc-class-time"><strong>9:15 AM <span>ET</span></strong><span>MONDAY–THURSDAY</span></div><button className="tc-primary" onClick={()=>act('Live Trading classroom')}><Play size={18} fill="currentColor"/> Open trading room <ArrowUpRight size={19}/></button></div><div className="tc-chart-side"><div className="tc-chart-top"><span>THE CLASSROOM BOARD</span><span>SPY / STUDY EXAMPLE</span></div><StudyChart/><div className="tc-chart-caption"><span>01</span><p>See the zone.<br/><strong>Ask why it matters.</strong></p></div></div></section>
  <aside className="tc-week"><p className="tc-overline">MAKE IT PART OF YOUR WEEK</p><h2>Your seat is saved.</h2><div className="tc-days">{['M','T','W','T','F'].map((d,i)=><span key={i} className={i<4?'class-day':''}>{d}{i<4&&<i/>}</span>)}</div><div className="tc-calendar-row"><div className="tc-date">MON<span>THU</span></div><div><h3>Live Trading</h3><p>9:15 AM Eastern</p></div></div><div className="tc-calendar-row"><div className="tc-date purple">WED<span>8 PM</span></div><div><h3>The evening class</h3><p>Slow it down. Go deeper.</p></div></div><button onClick={()=>act('Wednesday Class')}>Explore Wednesday class <ChevronRight size={18}/></button><p className="tc-small">Learn together. Questions welcome.</p></aside></div>
  <section className="tc-learn"><header className="tc-section-head"><div><p className="tc-overline">LESS SCROLLING. MORE “GOT IT.”</p><h2>What do you want to get better at?</h2></div><button onClick={()=>act('Lesson library')}>All lessons <ArrowUpRight size={17}/></button></header><div className="tc-interests" aria-label="Choose a learning focus">{['Supply & demand','Foundations','Learn with others'].map(s=><button key={s} aria-pressed={interest===s} onClick={()=>setInterest(s)}>{s}</button>)}</div><div className="tc-learning-grid"><button className={`tc-lesson-cover ${interest==='Foundations'?'foundation':interest==='Learn with others'?'together':''}`} onClick={()=>act(interest==='Supply & demand'?'Explore the lesson':interest==='Foundations'?'Beginner Bridge':'Community discussion')}><div className="tc-cover-top"><span>{interest==='Supply & demand'?'CHAPTER 04':interest==='Foundations'?'START HERE':'THE STUDENT LOUNGE'}</span><BookOpen size={22}/></div><h3>{interest==='Supply & demand'?<>Supply.<br/>Demand.<br/><span>Clarity.</span></>:interest==='Foundations'?<>Small steps.<br/>Strong<br/><span>foundations.</span></>:<>Your chart.<br/>Your question.<br/><span>Your people.</span></>}</h3><div className="tc-cover-bottom"><span>{interest==='Supply & demand'?'Supply & Demand Ep. 1':interest==='Foundations'?'Beginner Bridge':'Learn out loud'}</span><i><Play size={22} fill="currentColor"/></i></div></button><DailyChartStudy/></div></section>
  <section className="tc-social"><div className="tc-social-symbol"><MessageCircle size={30}/></div><div><p className="tc-overline">GOOD QUESTIONS BELONG HERE</p><h2>“Wait, why that zone?”</h2><p>That’s exactly the kind of question to bring to the lounge.</p></div><button onClick={()=>act('Community lounge')}>Meet your people <ArrowUpRight size={18}/></button></section>
  <section className="tc-coach"><div className="tc-coach-avatar">RZ</div><div><h3>One question holding you back?</h3><p>Bring it to a one-on-one. Leave with something clear to work on.</p></div><button onClick={()=>act('One-on-one training')}>Sit down with RZ <ArrowUpRight size={18}/></button></section>
</div>}
